security-actions/scan-docker-image/action.yml
To compensate for trivy's inability to take an image name with the  '--input' flag (an issue with trivy has been raised [HERE](https://github.com/aquasecurity/trivy/issues/3672)), these changes check for the existence of a docker.tar file and optionally pass the '--input' flag to the trivy action if a tar file is present.
=> fix(cd): only pass input flag to trivy action when docker tar is present

.github/dependabot.yml, .github/workflows/docker-image-scan.yml, .github/workflows/luacheck.yml, code-check-actions/luacheck/README.md, code-check-actions/luacheck/action.yml
Description:
1. The action will output an exit code based on the luacheck [https://luacheck.readthedocs.io/en/stable/cli.html#command-line-options] and will fail on any warnings/errors
2. Downstream implementations of this workflow must configure how to proceed with the workflow in case of failure. 
3. The action runs as a docker container and mounts the current workspace into the container with `luacheck` as entry point.
4. It will use any specified cli args and a `.luacheckrc` configuration file by default in the workspace dir.
=> feat(luacheck): Add luacode static analysis (#19)

.github/workflows/docker-image-scan.yml, code-check-actions/rustcheck/action.yml, security-actions/scan-docker-image/action.yml
- Revert SBOM action wrapper to 0.13.4 and use syft 0.75 until https://github.com/anchore/sbom-action/issues/419 is resolved.
- Add test to track dependency updates on multi-arch images.
=> Revert SBOM action

.github/workflows/auto-tagger.yml, .github/workflows/build-sdk-js.yml, .github/workflows/docker-image-scan.yml, .github/workflows/luacheck.yml, .github/workflows/rustcheck.yml
- Optimize workflow tests to run on tag creation instead of release published event
=> autoupdate major version tag on release

pr-previews/README.md
Missed this when moving README.md from `/shared-actions`  repos.
=> fix: action path in examples in readme for pr-preview actions

pr-previews/cleanup/action.yml
This is to attempt to cleanup newer PR preview package versions first. More chance to do something useful before 429 (rate limiting) error occurs.
=> fix: cleanup starting with newer PR versions [KHCP-7461]

.github/workflows/build-sdk-js.yml, README.md, code-build-actions/build-js-sdk/README.md, code-build-actions/build-js-sdk/action.yaml
This was a bug that led to "dry-run: false" to be ignored.
=> fix: use input string instead of boolean

code-check-actions/lua-lint/action.yml
This PR removes the global standard `-c/--compat` which means `--std max` in the luacheck command line argument list.
Having this argument defined will let luacheck ignore what defines in the luacheck rc configuration file, or other `--std` command line argument defined in `additional_args`. This problem currently breaks in any kong-ee PR's lint check(for example, https://github.com/Kong/kong-ee/pull/6283, https://github.com/Kong/kong-ee/pull/6267)
Removing this command line argument can fix the problems occurred in the repos that have customized luacheck rules defined in `luacheckrc`, and also does not influence the repos that not have standard defined, because luacheck's default standard is also `max`.
Ref: https://luacheck.readthedocs.io/en/stable/cli.html#command-line-options
=> fix(lint): do not specify global standard in luacheck command line arguments

pr-previews/cleanup/action.yml
`.time` in package details holds information for altready deleted versions. we need to skip those by doing lookup to `.versions`
=> fix: do not attempt to proceed already removed version [KHCP-7885]

.github/workflows/lua-lint.yml, code-check-actions/lua-lint/action.yml
- skip failing check run creation by dependabot only used while testing the shared action due when publishing lua check test results.
- Downstream repos always skip lua check when the actor is dependabot
- [Fix](https://github.com/EnricoMi/publish-unit-test-result-action?tab=readme-ov-file#support-fork-repositories-and-dependabot-branches) requires creating a separate workflow for publishing test results which can be skipped for testing purposes for dependabot branches
=> skip  failing check run for dependabot branches during luacheck report publishing

security-actions/sca/action.yml
Syft by default looks for configuration files in the PATH where it is run and needs an explicit path for config in case of Github action runners to pick a custom configuration specified in a checkout scan repository.
Helps to specify overrides / select catalogers / ignore rules / exclude paths as required for tuning.
Refer [Syft custom configuration](https://github.com/anchore/syft?tab=readme-ov-file#configuration) to specify explicit [input](https://github.com/anchore/sbom-action/blob/main/action.yml#L76-L78) for the SBOM action
=> feat: Add optional "config" input to sca syft action

security-actions/sca/action.yml, security-actions/scan-docker-image/action.yml, security-actions/scan-docker-image/scripts/scan-metadata.sh
Copy over the scan steps for the docker image scan action without reusing from a local action within the same repo
Deprecate image inputs for SCA action.
- Reusing a local shared action within a shared action that is invoked from some other caller workflow ina different repository has a [limitation](https://github.com/orgs/community/discussions/41927) where the `uses` block doesn't allow for any variables interpolation. 
- Using symlink workaround works well on GH-hosted runners (with a hardcoded path in uses block) but doesn't run when the self-hosted runners / Windows OS when workspace paths are different.
=> ci(.github): deprecate reuse of sca scan action in docker image scan

security-actions/sign-docker-image/action.yml
Current version logs warnings:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: docker/login-action@v2.1.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
=> update docker/login-action to v3.0.0

.github/dependabot.yml, security-actions/sign-docker-image/action.yml
Failure of build pipelines due to missing dependabot config for sign image action and due to deprecated cosign version 2.2.1.
```
getting signer: getting key from Fulcio: getting CTFE public keys: updating local metadata and targets: error updating to TUF remote mirror: invalid key
```
Ex: 
https://github.com/Kong/kong-ee/actions/runs/8345534028/job/22864504377#step:11:619
https://github.com/slsa-framework/slsa-github-generator/issues/3350
https://github.com/Kong/public-shared-actions/actions/runs/8353600274
Bump cosign installaer to use v2.2.3 cosign
=> ci(deps): bump cosign to v2.2.3 to avoid sigstore TUF invalid key issue

.github/workflows/docker-image-provenance.yml
Test workflow for validating and capturing SLSA Container image provenance generator workflow issues.
Needs to merge into the main to run and test this workflow.
=> ci(.github): Add SLSA docker image provenance test workflow

.github/workflows/dir-scan.yml, .github/workflows/docker-image-scan.yml, security-actions/sca/README.md, security-actions/sca/action.yml, security-actions/scan-docker-image/README.md, security-actions/scan-docker-image/action.yml
1. This PR provides an optional input parameter to **UPLOAD** `SBOM` to existing release assets / tags.
2. This will **NOT UPLOAD** the below assets to GH releases:
- `CVE / SCA scan report`
- `Trivy CIS report`
Creating a tag / release on this repo, the workflows for images and directory scans should upload a `test.*.sbom.*` assets.
=> feat(sbom): option to publish sbom to tags / GH release assets

.github/workflows/dir-scan.yml, .github/workflows/docker-image-scan.yml, security-actions/sca/action.yml, security-actions/scan-docker-image/action.yml, security-actions/scan-rust/action.yml
- Grype action caches the db on its first invocation at `cache-dir: "$XDG_CACHE_HOME/grype/db"` as per [config](https://github.com/anchore/grype?tab=readme-ov-file#configuration) file
- Optimize build time by avoiding grype db downloads during multiple subsequent runs of `anchore/scan-action` for CVE analysis. 
- This improvement WILL NOT FIX the [read timeout issue](https://github.com/anchore/scan-action/issues/306) during the first invocation of the action
=> Avoid Grype DB downloads during subsequent invocations of grype scan-action

security-actions/sign-docker-image/README.md, security-actions/sign-docker-image/action.yml
This PR allows Cosign  to login to two different registres to `pull  image from 1st reg -> sign -> push image signatures to dockerhub`. 
Currently signing action works as long as  image and image signatures are pushed to same registry using single set of credentials.
However sometimes images can be hosted in other registries like github container registry. In this case cosign needs to pull from the private / public image registries and publish signatures to different registry (`docker.io`)
=> add separate signature registry opts for image signing

.github/workflows/docker-image-scan.yml, security-actions/sca/action.yml, security-actions/scan-docker-image/action.yml
Fix to download assets during workflow run and compatible with download-artifact@v4
Fixes: https://github.com/anchore/sbom-action/issues/434
=> Bump sbom-action from v.0.15.11 to v0.16.0

.github/workflows/dir-scan.yml, .github/workflows/docker-image-scan.yml, security-actions/sca/action.yml, security-actions/scan-docker-image/action.yml
Fixes #140 
- Include graceful error /  warning message based on cache / db availability
- when `enforcement` / input `build_fail` is `false`, CVE analysis is **skipped**  
-  when  `enforcement` / input `build_fail` is `true`, CVE analysis will  **failed / error the he downstream caller**
=> Run CVE analysis when DB cache or upstream cdn is live

security-actions/sca/action.yml
- Fixes the issue to restore old cache when exists
- On DB drift, updates DB
- Save any DB updates back to same cache key and then use it
Issue:
Cache for main branch before PR is merged is stale (5 days old)
After PR is merged into main branch (Refer to action run after PR is merged for main branch):
=> save grype db cache on updates to avoid using stale cache db

security-actions/scan-docker-image/action.yml
- Update to Step "Generate docker-cis JSON report", removed severity flag as it was causing warnings "unknown severity option: unknown severity: FALSE"
- Update to Step "Inspect docker-cis report", removed severity flag as it was causing warnings "unknown severity option: unknown severity: FALSE"
- This severity flag is not being used at this point. Trivy uses this flag to restrict the scan to specific severity levels
- Because of no explicit severity flag, shared action uses value of global_enforce_build_failure env defined in our scripts
=> fix: omitted severity flags in docker image scan action

.github/workflows/docker-image-scan.yml, security-actions/sca/action.yml, security-actions/scan-docker-image/action.yml
**Summary:**
This PR introduces a new input parameter `skip_grype_db_cache` to the sca/scan-docker-image action. This option allows users to skip the caching of the Grype DB during the SBOM (Software Bill of Materials) scanning process. By setting this input to `true`, both the restoration of existing caches and the saving of new cache updates will be bypassed.
- Added a `skip_grype_db_cache` input parameter to the action.
- Type: `choice`
- Options:`true`, `false`
- Default: `false`
- Updated the workflow logic to conditionally skip the Grype DB caching steps based on the value of `skip_grype_db_cache`.
- When `skip_grype_db_cache` is set to `true`, the action will:
- Skip restoring any existing Grype DB cache.
- Skip saving any updates to the Grype DB cache.
To trigger the skip cache …
=> SEC-1176 - Option to skip Grype DB caching and tradeoff to use Grype CDN

security-actions/sca/action.yml, security-actions/scan-docker-image/action.yml
only use cache during cdn failures and set explicitly
- Refer https://github.com/Kong/public-shared-actions/issues/151
- Grype has updated their CDN which seems NOT flaky as per https://anchorecommunity.discourse.group/t/grype-vulnerability-database-hosting-update/75
Uses option 1 to skip cache and default to CDN until the issue is fixed and grype CDN is flaky again
=> Defaulting to use grype cdn and skip cache by default

code-check-actions/lua-lint/action.yml
This will enable to use the problem matcher on GitHub.
=> feat(lua-lint): Add `inputs.print_results` to lua-lint action.

.github/dependabot.yml, .github/workflows/semgrep.yml, security-actions/semgrep/action.yml
Why to update?
Semgrep is giving following message in the scan runs `A new version of Semgrep is available. See https://semgrep.dev/docs/upgrading` 
Note:
We use latest version tag of the image but looks like semgrep has made few new tag releases but have not rolled out their `Latest` tag to the latest version that is `1.86.0`
=> feat(SEC-1211): update semgrep version

slack-actions/workflow-notification/action.yaml
Example usage:
```yaml
- name: Get aggregate Workflow status
uses: technote-space/workflow-conclusion-action@v3
- name: Send notification
uses: Kong/public-shared-actions/slack-actions/workflow-notification@v1
with:
slack-webhook-url: ${{ env.WORKFLOW_CONCLUSION == 'failure' && secrets.SLACK_WEBHOOK_URL_ALERT || secrets.SLACK_WEBHOOK_URL_NOTIFY }}
status: ${{ env.WORKFLOW_CONCLUSION == 'failure' && 'failure' || 'success' }}
```
=> feat: slack workflow conclusion notifications

slack-actions/workflow-notification/action.yaml
Fix `input.status-message` should be `input-success-message`
Apparently I can't code on Friday
=> fix: success not status

.github/workflows/test-slack-actions.yaml, slack-actions/workflow-notification/action.yaml
Add support for custom payloads and additional 'status' values.
`inputs.status` now accepts any one of: `success`, `failure`, `cancelled`, or `skipped` which correspond to the related `{status}-message` inputs.
You can set the `payload` input with content via [Slack Block Kit Builder](https://app.slack.com/block-kit-builder/) that will override the `header` `*-message` and other inputs to customize your notification.
```yaml
- name: Post 'success' notification with custom payload
uses: ./slack-actions/workflow-notification
with:
slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_NOTIFY_SLACK_NOTIFICATION_TEST }}
status: 'success'
payload: |
{
"blocks": [
{
"type": "header",
"text": {
"type": "plain_text",
"text": "[TEST] Kong/public-shared-actions",
"emoji": true
}
},
{
"type": "context", …
```
=> feat(slack): new workflow inputs

security-actions/scan-rust/action.yml, security-actions/semgrep/action.yml
no longer depends on versions below Node.js 20.
KAG-5461
=> chore(deps): bump github/codeql-action/upload-sarif from v2 to v3

.github/workflows/docker-image-scan.yml, security-actions/scan-docker-image/README.md, security-actions/scan-docker-image/action.yml
input which allows caching the Trivy DB to get around rate limiting issues
Trivy (ab)uses GHCR OCI as it's config update mechanism, and this is being heavily (targeted) rate limited by GitHub.
Inspired by https://github.com/aquasecurity/trivy/discussions/7591, this PR adds two optional arguments to the `security-actions/scan-docker-image` image that allows us to skip fetching fro GHCR completely:
```
trivy_db_cache:
description: 'GitHub repository containing Trivy DB cache (format: owner/repo@ref). Database should be named `db.tar.gz` on the default branch.'
required: false
trivy_db_cache_token:
description: 'Token for accessing `trivy_db_cache`.'
required: false
```
When provided, we will checkout the specific repo's branch using the PAT, look for a `db.tar.gz` file from it and untar it …
=> feat(security-actions/scan-docker-image): support `trivy_db_cache` as alternate

.github/workflows/release.yml
- Removed explicit checkout step.
=> fix(release): remove explicit headref checkout step

security-actions/sign-docker-image/action.yml
In Kuma, we occasionally encounter an issue while signing images, as seen in this workflow: [GitHub Actions Run](https://github.com/kumahq/kuma/actions/runs/12741786325/job/35513880546).
It appears that the token sometimes enters a verification mode, prompting the following message:
> Enter the verification code DZXT-XKLG in your browser at: https://oauth2.sigstore.dev/auth/device?user_code=DZXT-XKLG.
Upon investigating, I found a relevant discussion on the issue: [Sigstore Cosign Issue #1258](https://github.com/sigstore/cosign/issues/1258#issuecomment-1684227935).
```
Retrieving signed certificate...
Non-interactive mode detected, using device flow.
Enter the verification code DZXT-XKLG in your browser at: https://oauth2.sigstore.dev/auth/device?user_code=DZXT-XKLG
Code will be valid for …
```
=> chore(sign-docker-image): set issuer to github-action

.github/workflows/release.yml
Refer: https://github.com/orgs/community/discussions/26238
CI Failed run: https://github.com/Kong/public-shared-actions/actions/runs/12773616835
Published run: https://github.com/Kong/public-shared-actions/actions/runs/12773627945
=> fix(ci): publish release only when ci workflow succeeds

.github/workflows/ci.yml, .github/workflows/release.yml
Update CI and release workflow to use custom payload to support custom fields such as TriggeredByCommit, Release commit, Event Name, Commit Author.
This also allows us to add any other field required in the future without modifying the local slack shared action.
Why this is needed?
- The existing Slack shared action only supports few fields and this release and CI slack notifications required some custom fields as mentioned above.
=> chore(ci): update slack message

commitlint.config.js
- Updates commitlint config file to ignore commit messages in the format `github-actions(deps): bump anchore/scan-action from 4.1.2 to 6.1.0`. These commit messages are generally used by Dependabot while raise PRs for version bump for upstream dependencies. 
The CI workflows have been failing for Dependabot. Ref below failed example https://github.com/Kong/public-shared-actions/actions/runs/12938518475/job/36088812115?pr=217
```
Error: You have commit messages with errors
⧗   input: github-actions(deps): bump anchore/scan-action in /security-actions/sca
Bumps [anchore/scan-action](https://github.com/anchore/scan-action) from 4.1.2 to 6.1.0.
- [Release notes](https://github.com/anchore/scan-action/releases)
- [Changelog](https://github.com/anchore/scan-action/blob/main/RELEASE.md)
- …
```
=> feat(deps): ignore commitlint check for dependabot messages

security-actions/scan-docker-image/action.yml
- Bump trivy version to  [v0.58.2](https://github.com/aquasecurity/trivy/releases/tag/v0.58.2)
- Include [fix](https://github.com/aquasecurity/trivy/blob/release/v0.58/CHANGELOG.md#bug-fixes-1) for intermittent [UNKNOWN_BLOB error](https://github.com/Kong/kauth-pdp/actions/runs/13661154051/job/38192998446) during image DB pulls using automatic fallback to other DB mirror registries.
=> chore(ci): bump trivy from v0.57.1 to v0.58.2

security-actions/scan-docker-image/action.yml
The Docker CIS [image scan ](https://github.com/Kong/kong-ee/actions/runs/13834989248/job/38711656958) for `amazonlinux 2023` failed. I'm not sure if that's the actual error.
The trivy command [--exit-code 1](https://github.com/Kong/kong-ee/actions/runs/13834989248/job/38714374490#step:7:504)  was ideally supposed to be applied on failures in [CIS compliance checks](https://github.com/Kong/kong-ee/actions/runs/13834989248/job/38714374490#step:7:501). 
The result from [Docker image CIS checks](https://github.com/Kong/kong-ee/actions/runs/13834989248/job/38714374490#step:7:529)  doesn't have any failures.
However, the output is deceptive, and only displays the results of compliance checks and NOT the findings from default scanners that misleads us why the --exit-code 1 was applied to fail …
=> fix(scan-docker-image): disable trivy exit-code for docker-cis

security-actions/scan-docker-image/action.yml
This PR aligns the outputs defined in the shell script to those described in `action.yml`.
=> fix(scan): grype outputs in image scan

README.md
Update README on using shared Renovate config for PSA version management in downstream application workflows.
=> chore(docs): update README on using shared Renovate config

.github/workflows/docker-image-provenance.yml, .github/workflows/docker-image-sign.yml, security-actions/sign-docker-image/README.md
- Migrate `Kongcloud` Dockerhub Repositories
- Use ECR + Kong internal notary to store signatures and provenance artifacts.
=> chore(ci): use private ecr and dockerhub notary for ci

README.md, code-build-actions/build-js-sdk/package.json, code-check-actions/lua-lint/package.json, code-check-actions/rust-lint/package.json, lerna.json, pr-previews/cleanup/package.json, pr-previews/up-to-date/package.json, pr-previews/validate/package.json, security-actions/sca/package.json, security-actions/scan-docker-image/package.json, security-actions/scan-gh-workflows/package.json, security-actions/scan-rust/package.json, security-actions/sign-docker-image/package.json, slack-actions/workflow-notification/package.json
- Change to use 'unscoped' package naming convention for release tags
- standardize release tags conventions across internal and public shared actions
- helps streamline standard preset for renovate configs across internal and public shared actions
- Although SHA is recommended over using release tag names,  it avoids the GH nuance of failing to fetch release tags with the format: `Kong/public-shared-actions/security-actions/scan-docker-image@@security-actions/sca@4.1.4` including `double @`
Applications and Package managers using:
- Release Tag names will need update the package names to new format
- Pinned SHA  are NOT affected
=> chore(ci): use unscoped package names for git release tags

.github/workflows/docker-image-scan.yml, security-actions/scan-docker-image/README.md, security-actions/scan-docker-image/action.yml
Expose the `by-cve` flag to allow downstream workflows to orient vulnerability results by CVE identifiers instead of GHSA identifiers.
* Add `by-cve` input parameter to the Grype scanning action
=> feat(scan-docker-image): add by-cve flag to organise results by CVE

security-actions/sca/action.yml
In case in a repo we are not over the 10GB limit for GitHub actions cache, thus the security database never gets outdated, the database never gets updated. see this [run](https://github.com/openmeterio/openmeter/actions/runs/18274917328/job/52024699148)
This patch makes sure to use a cache key that is day specific to force one fetch per day.
This is a common pattern used by other solutions:
- https://github.com/aquasecurity/trivy-action/blob/master/action.yaml#L135C1-L146
- golangcilint
Right now given on cache hit we are not updating the DB, I am not using the key/restore-key distinction.
=> fix: SCA action grype DB should be downloaded at least daily
